### ISSUE TITLE
Instagram original quality

### ISSUE THREAD

**Issue by 89z** [michabirklbauer/instagram_downloader#9]
If I use InstagramDowloader with this page:

https://www.instagram.com/p/CZVEugIPkVn/

I get 1080 x 1080 image. If I use a request like this:

~~~
GET /p/CZVEugIPkVn/?__a=1 HTTP/1.1
Host: www.instagram.com
User-Agent: Instagram 220.0.0.16.115 Android (99/9; density; 9999x9999; brand; model; device; platform
Authorization: Bearer IGT:2:eyJkc191c2VyX2lkIjoiNDkzNzgxNzEzMzQiLCJzZXNzaW9ua...
~~~

I can get original quality, 1241 x 1241. Is it possible for InstagramDownloader to get the better quality?

**Comment by michabirklbauer** [comment]
Yes, you can get the original quality by specifying a cookie file:
See here: https://github.com/michabirklbauer/instagram_downloader#usage
The cookie is used to authenticate the API request with Instagram and they will send the highest resolution available. Without the cookie the request is sent anonymously and Instagram will only send lower resolution ones, in this case 1080x1080.

**Comment by 89z** [comment]
Are you sure that anonymous even works any more? From my own testing, anonymous requests dont work at all any more, with any Instagram API. Personally I only have light usage, nothing abusing, but even I am getting consistently blocks when trying anonymous request. Even if I only make one request per hour. Also getting errors now with this tool as well:

~~~
PS D:\Desktop\instagram_downloader-master> python.exe instaload.py -url https://www.instagram.com/p/CZVEugIPkVn/
ERROR: Failed to load json data!
Unknown ERROR encountered: Download may have failed!
1
~~~

**Comment by michabirklbauer** [comment]
It still works for me, just checked. But only for a few posts and then will also get blocked. I don't know what the exact limit is and if the limit is hourly or daily. Also could be dependent on location. But yes, anonymous request are definitely not the way to go anymore. Instagram is becoming very strict about everything.
